// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEC3rRelxFpfnH4b10zjMc6uxLfj7yBSU',
    appId: '1:213409740927:web:1eeef649398292e6da274a',
    messagingSenderId: '213409740927',
    projectId: 'luckybikey-281fa',
    authDomain: 'luckybikey-281fa.firebaseapp.com',
    storageBucket: 'luckybikey-281fa.appspot.com',
    measurementId: 'G-BKMJ3H3PMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4R_-rRjKd6n1ExdrDkNdSf7NCJW16R0',
    appId: '1:213409740927:android:c7a10ffcd1ee67dcda274a',
    messagingSenderId: '213409740927',
    projectId: 'luckybikey-281fa',
    storageBucket: 'luckybikey-281fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHW0eJrMwOwFzou5rqTwBsNhbhBRpzgXE',
    appId: '1:213409740927:ios:e72dd667ee01b46eda274a',
    messagingSenderId: '213409740927',
    projectId: 'luckybikey-281fa',
    storageBucket: 'luckybikey-281fa.appspot.com',
    iosClientId: '213409740927-be7un6hitv8d5g77no62tc1qbhor22nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.luckybiky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHW0eJrMwOwFzou5rqTwBsNhbhBRpzgXE',
    appId: '1:213409740927:ios:e72dd667ee01b46eda274a',
    messagingSenderId: '213409740927',
    projectId: 'luckybikey-281fa',
    storageBucket: 'luckybikey-281fa.appspot.com',
    iosClientId: '213409740927-be7un6hitv8d5g77no62tc1qbhor22nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.luckybiky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEC3rRelxFpfnH4b10zjMc6uxLfj7yBSU',
    appId: '1:213409740927:web:934de44689be6dd3da274a',
    messagingSenderId: '213409740927',
    projectId: 'luckybikey-281fa',
    authDomain: 'luckybikey-281fa.firebaseapp.com',
    storageBucket: 'luckybikey-281fa.appspot.com',
    measurementId: 'G-P1M8VWGCWP',
  );

}